- name: fronted
  hosts: all
  become: yes
  tasks:
    - name: installing the nginx server
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: copying the config file
      ansible.builtin.copy:
        src: expens.conf
        dest: /etc/nginx/default.d/expens.conf
        remote_src: yes
    - name: removing directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent
    - name: removing directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: Directory
    - name: Download and unarchive a file
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes
    - name: starting the service
      ansible.builtin.service:
        name: nginx
        state: restarted
