
    - name: disabling node js 18
      ansible.builtin.dnf:
        name: nodejs
        state: absent

    - name: enabling the nodejs 18
      ansible.builtin.shell: dnf module enable nodejs:18 -y

    - name: installing the nodejs:18
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: adding application user
      ansible.builtin.user:
        name: expense


    - name: creating the directy with the import
      ansible.builtin.import_role:
        name: common
        tasks_from: expensecc
      vars:
        appli_dir: /app
        component: backend

    - name: changing the directory & installing the dependence
      ansible.builtin.shell: npm install
      args:
        chdir: /app

    - name: copying the backend service file
      ansible.builtin.template:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: starting the systemd file
      ansible.builtin.systemd:
        name: backend
        daemon_reload: true
        state: restarted
        enabled: true

    - name: installing mysql agent
      ansible.builtin.dnf:
        name: mysql
        state: present

    - name: loading scheme
      ansible.builtin.shell: mysql -h "{{ lookup('aws_ssm', 'mysql', region='us-east-1') }}" -uroot -p"{{ lookup('aws_ssm', 'mysqlpassword', region='us-east-1') }}" < /app/schema/backend.sql


