
    - name: installing the nginx server
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: copying the config file
      ansible.builtin.template:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: removing directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: creating the directory with import app
      ansible.builtin.import_role:
        name: common
        tasks_from: expensecc
      vars:
        appli_dir: /usr/share/nginx/html
        component: frontend

    - name: starting the service
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true
